function linejoindrawScreen(){
	//画布背景色为白色不利于辨识，填充一个有颜色的区域便于标示。
	context.fillStyle="#aaaaaa";
	context.fillRect(0,0,500,500);
	//高级线段绘制，圆形端点，斜角链接，在画布左上角
	context.strokeStyle="red";
	context.lineWidth=10;
	context.lineJoin='bevel';//定义两条线相交产生的拐角，可将其称为连接。在连接处创建一个填充三角形
	//miter为默认值，在连接处边缘延长相接。miterLimit是角长和线宽所允许的最大比例（默认10）
	//bevel连接处是一个对角线斜角，round连接处是一个圆
	context.lineCap='round';
	context.beginPath();
	context.moveTo(0,0);
	context.lineTo(25,0);
	context.lineTo(25,25);
	context.stroke();
	context.closePath();
	//圆形端点，斜角连接，不在画布左上角
	context.beginPath();
	context.moveTo(10,50);
	context.lineTo(35,50);
	context.lineTo(35,75);
	context.stroke();
	context.closePath();
	//平直端点，圆形连接，不在画布左上角
	context.lineJoin="round";
	context.lineCap='butt';
	context.beginPath();
	context.moveTo(10,100);
	context.lineTo(35,100);
	context.lineTo(35,125);
	context.stroke();
}